# config/cable.yml

development:
  adapter: async

test:
  adapter: test

production:
  adapter: solid_cable
  # Usa a mesma conexão definida no DATABASE_URL
  # (já configurada em config/database.yml)
  url: <%= ENV["DATABASE_URL"] %>
  polling_interval: 0.1.seconds
  message_retention: 1.day
