default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geomatch_development

test:
  <<: *default
  database: geomatch_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  # Solid Queue precisa disso ðŸ‘‡
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

cable:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>