default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "sua_senha_local") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: geomatch_development

test:
  <<: *default
  database: geomatch_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# ðŸ”§ Corrige o erro do SolidCable
cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
